export type CommitteeCharacterId =
  | 'marek'
  | 'isa'
  | 'tom'
  | 'will'
  | 'finance'
  | 'david'
  | 'jakub'
  | 'caroline'
  | 'hikaru'
  | 'hadi'
  | 'ivan';

export type CommitteePose = 'celebrate' | 'explain' | 'encourage';
export type CommitteeTopic =
  | 'out'
  | 'damaged'
  | 'goal'
  | 'own-goal'
  | 'pushed-out'
  | 'restart'
  | 'technical'
  | 'interference'
  | 'progress'
  | 'general';
export type CommitteeOutcome =
  | 'correct'
  | 'retry'
  | 'recorded'
  | 'study'
  | 'complete';

export type CommitteeCharacter = Readonly<{
  id: CommitteeCharacterId;
  name: string;
  role: string;
  accent: string;
  bio: string;
  asset: string;
}>;

export type CommitteeDialogue = Readonly<{
  id: string;
  character: CommitteeCharacterId;
  topic: CommitteeTopic;
  outcomes: readonly CommitteeOutcome[];
  pose: CommitteePose;
  text: string;
}>;

export const COMMITTEE_VOICE_DISCLAIMER =
  'Playful fictional committee voices, not real quotations or official rule decisions; the sourced feedback remains authoritative.';

export const CHARACTERS: readonly CommitteeCharacter[] = [
  {
    id: 'marek',
    name: 'Marek',
    role: 'Vim-powered idea machine',
    accent: '#38bdf8',
    bio: 'A joyful Slido-shirt coder juggling five Vim terminals and an imaginary unlimited token budget.',
    asset: '/characters/marek.png',
  },
  {
    id: 'isa',
    name: 'Isa',
    role: 'Committee chair, rulebook ready',
    accent: '#fb923c',
    bio: 'A fair Dutch committee chair with a big beard, a well-read rulebook, and a literal chair to match the job title.',
    asset: '/characters/isa.png',
  },
  {
    id: 'tom',
    name: 'Tom',
    role: 'Rescue and rocket specialist',
    accent: '#a78bfa',
    bio: 'A helpful rescue-committee visitor bringing maze robots, rocket ideas, and black rectangular glasses.',
    asset: '/characters/tom.png',
  },
  {
    id: 'will',
    name: 'Will',
    role: 'Down Under soccer guide',
    accent: '#facc15',
    bio: 'An Australian RCJ guide with a kangaroo companion and a cheerful view from the other side of the world.',
    asset: '/characters/will.png',
  },
  {
    id: 'finance',
    name: 'Roberto',
    role: 'Spreadsheet strategist',
    accent: '#34d399',
    bio: 'A suited finance character treating training like a very enthusiastic spreadsheet, with no real money involved.',
    asset: '/characters/finance.png',
  },
  {
    id: 'david',
    name: 'David',
    role: 'Referee training conductor',
    accent: '#f87171',
    bio: 'A German referee mentor in stripes who loves clear teaching, precise timetables, and trains.',
    asset: '/characters/david.png',
  },
  {
    id: 'jakub',
    name: 'Jakub',
    role: 'RoboFuse technical multitasker',
    accent: '#22d3ee',
    bio: 'Black T-shirt, tiny orange IR balls, ESP/OLED modules, livestreams, and poles almost longer than the to-do list.',
    asset: '/characters/jakub.png',
  },
  {
    id: 'caroline',
    name: 'Caroline',
    role: 'Livestream and task-list hero',
    accent: '#f472b6',
    bio: 'Jakub’s partner and witty livestream teammate, keeping the audience, task list, and big ideas in focus.',
    asset: '/characters/caroline.png',
  },
  {
    id: 'hikaru',
    name: 'Hikaru',
    role: 'Three-generation soldering samurai',
    accent: '#ef4444',
    bio: 'An anime-inspired maker with IoT gadgets and fictional grandpa-and-baby sidekicks. Three generations, one missing screwdriver.',
    asset: '/characters/hikaru.png',
  },
  {
    id: 'hadi',
    name: 'Hadi',
    role: 'Blockchain hype, referee focus',
    accent: '#eab308',
    bio: 'A cheerful crypto enthusiast in a blue suit. Imaginary tokens, real enthusiasm for learning; no investment advice.',
    asset: '/characters/hadi.png',
  },
  {
    id: 'ivan',
    name: 'Ivan',
    role: 'Touchline party starter',
    accent: '#a3e635',
    bio: 'A Croatian party host with an olive shirt, a red lanyard, and a playlist for every replay. Confetti stays off the field.',
    asset: '/characters/ivan.png',
  },
];

const line = (
  character: CommitteeCharacterId,
  slug: string,
  topic: CommitteeTopic,
  outcomes: readonly CommitteeOutcome[],
  pose: CommitteePose,
  text: string,
): CommitteeDialogue => ({
  id: `${character}-${slug}`,
  character,
  topic,
  outcomes,
  pose,
  text,
});

// Recorded lines are deliberately topic-neutral: continuous play must never
// reveal correctness or an unseen event before the referee opens the review.
export const DIALOGUE: readonly CommitteeDialogue[] = [
  line(
    'hikaru',
    'out-1',
    'out',
    ['study', 'correct'],
    'explain',
    'Out of bounds? Even three generations of soldering samurai cannot solder extra field onto the wall.',
  ),
  line(
    'hikaru',
    'damaged-2',
    'damaged',
    ['study', 'retry'],
    'encourage',
    'Time to inspect the robot. Grandpa brought tools; the baby brought moral support and a toy screwdriver.',
  ),
  line(
    'hikaru',
    'goal-3',
    'goal',
    ['study', 'correct'],
    'celebrate',
    'Check the goal evidence. My IoT scoreboard is excited, but it does not get to referee.',
  ),
  line(
    'hikaru',
    'own-goal-4',
    'own-goal',
    ['study', 'retry'],
    'encourage',
    'Check which goal the ball entered. Swapping the wires is not a scoreboard correction!',
  ),
  line(
    'hikaru',
    'pushed-out-5',
    'pushed-out',
    ['study', 'correct'],
    'explain',
    'Replay the contact. Three generations watching, and Grandpa still asks to see it from another angle.',
  ),
  line(
    'hikaru',
    'restart-6',
    'restart',
    ['study', 'retry'],
    'explain',
    'Check the restart procedure. The baby pressed reset on the toy; please do not copy that strategy.',
  ),
  line(
    'hikaru',
    'technical-7',
    'technical',
    ['study', 'correct'],
    'explain',
    'Inspect first, solder later. My most powerful IoT feature is still checking whether it is switched on.',
  ),
  line(
    'hikaru',
    'interference-8',
    'interference',
    ['study', 'retry'],
    'encourage',
    'Keep the field clear. Our family workshop has visitors too, but nobody gets to poke the experiment.',
  ),
  line(
    'hikaru',
    'progress-9',
    'progress',
    ['study', 'complete'],
    'celebrate',
    'Another learning milestone! Grandpa is proud. The baby has eaten the imaginary instruction manual.',
  ),
  line(
    'hikaru',
    'general-10',
    'general',
    ['correct'],
    'celebrate',
    'Beautiful work! Three generations of soldering samurai raise their screwdrivers in your honour.',
  ),
  line(
    'hikaru',
    'general-11',
    'general',
    ['retry'],
    'encourage',
    'Another look, another lesson. Even a soldering samurai occasionally connects the learning wires backwards.',
  ),
  line(
    'hikaru',
    'general-12',
    'general',
    ['recorded'],
    'explain',
    'Decision recorded in the workshop log. Grandpa has sharpened his pencil, not his opinions.',
  ),
  line(
    'hikaru',
    'general-13',
    'general',
    ['recorded'],
    'encourage',
    'Decision saved. The tiny workshop assistant is guarding the notebook with a very serious baby face.',
  ),
  line(
    'hikaru',
    'general-14',
    'general',
    ['complete'],
    'celebrate',
    'Session finished! Tools down, review open. The family workshop has ordered a round of imaginary tea.',
  ),
  line(
    'hikaru',
    'general-15',
    'general',
    ['study'],
    'explain',
    'Read, observe, test. It is like building a circuit, except the rules do not smell of solder.',
  ),
  line(
    'hadi',
    'out-16',
    'out',
    ['study', 'correct'],
    'explain',
    'Out of bounds has entered the chat. Sadly, my imaginary token cannot buy more field.',
  ),
  line(
    'hadi',
    'damaged-17',
    'damaged',
    ['study', 'retry'],
    'encourage',
    'Inspect that robot before pitching its comeback. A whitepaper is not a repair kit.',
  ),
  line(
    'hadi',
    'goal-18',
    'goal',
    ['study', 'correct'],
    'celebrate',
    'Check the goal, then celebrate. My scoreboard does not accept speculative deposits.',
  ),
  line(
    'hadi',
    'own-goal-19',
    'own-goal',
    ['study', 'retry'],
    'encourage',
    'Follow the ball to the goal it entered. Calling it a strategic transfer will not change the replay.',
  ),
  line(
    'hadi',
    'pushed-out-20',
    'pushed-out',
    ['study', 'correct'],
    'explain',
    'Check who made contact. My blockchain records transactions; this replay records actual pushes.',
  ),
  line(
    'hadi',
    'restart-21',
    'restart',
    ['study', 'retry'],
    'explain',
    'Check the restart steps. A fresh match phase does not need a new token launch.',
  ),
  line(
    'hadi',
    'technical-22',
    'technical',
    ['study', 'correct'],
    'explain',
    'Test the hardware, not the hype. Even my imaginary blockchain needs the power cable plugged in.',
  ),
  line(
    'hadi',
    'interference-23',
    'interference',
    ['study', 'retry'],
    'encourage',
    'Keep outside influence off the field. This match is not taking sponsorship bids from my imaginary coin.',
  ),
  line(
    'hadi',
    'progress-24',
    'progress',
    ['study', 'complete'],
    'celebrate',
    'Learning portfolio expanded! Diversify with another rule, not another imaginary coin.',
  ),
  line(
    'hadi',
    'general-25',
    'general',
    ['correct'],
    'celebrate',
    'Excellent thinking! I am extremely bullish on checking the evidence. No tokens required.',
  ),
  line(
    'hadi',
    'general-26',
    'general',
    ['retry'],
    'encourage',
    'Another look is free. My imaginary coin has fees; learning from a replay does not.',
  ),
  line(
    'hadi',
    'general-27',
    'general',
    ['recorded'],
    'explain',
    'Decision logged. No wallet, no gas fee, just a very enthusiastic imaginary ledger.',
  ),
  line(
    'hadi',
    'general-28',
    'general',
    ['recorded'],
    'encourage',
    'Decision saved in the training log. My imaginary coin has been asked to stop advertising.',
  ),
  line(
    'hadi',
    'general-29',
    'general',
    ['complete'],
    'celebrate',
    'Session complete! Time to audit the replay. This is the only audit where I bring imaginary confetti.',
  ),
  line(
    'hadi',
    'general-30',
    'general',
    ['study'],
    'explain',
    'Read the rule before the hype. I have a whole imaginary whitepaper explaining why reading helps.',
  ),
  line(
    'ivan',
    'out-31',
    'out',
    ['study', 'correct'],
    'explain',
    'Out of bounds? The after-party is off the field too, but this is a match, not the guest list.',
  ),
  line(
    'ivan',
    'damaged-32',
    'damaged',
    ['study', 'retry'],
    'encourage',
    'Give the robot a careful check. The DJ can fix an awkward silence, not a loose wheel.',
  ),
  line(
    'ivan',
    'goal-33',
    'goal',
    ['study', 'correct'],
    'celebrate',
    'Check the goal evidence before the victory dance. I have already rehearsed three unnecessarily dramatic moves.',
  ),
  line(
    'ivan',
    'own-goal-34',
    'own-goal',
    ['study', 'retry'],
    'encourage',
    'Check the goal end. Even my most chaotic playlist does not get to swap the teams.',
  ),
  line(
    'ivan',
    'pushed-out-35',
    'pushed-out',
    ['study', 'correct'],
    'explain',
    'Replay that contact. This is robot soccer, not the front row at my imaginary concert.',
  ),
  line(
    'ivan',
    'restart-36',
    'restart',
    ['study', 'retry'],
    'explain',
    'Check the restart setup. I can cue the music, but the robots need the match procedure, not a countdown remix.',
  ),
  line(
    'ivan',
    'technical-37',
    'technical',
    ['study', 'correct'],
    'explain',
    'Test the equipment. My party trick is finding the cable everyone forgot to plug in.',
  ),
  line(
    'ivan',
    'interference-38',
    'interference',
    ['study', 'retry'],
    'encourage',
    'Cheer from the sidelines. My confetti has strict instructions not to become a fifth robot.',
  ),
  line(
    'ivan',
    'progress-39',
    'progress',
    ['study', 'complete'],
    'celebrate',
    'Another learning milestone! Somewhere in Croatia, an imaginary disco ball just nodded approvingly.',
  ),
  line(
    'ivan',
    'general-40',
    'general',
    ['correct'],
    'celebrate',
    'That deserves a tiny victory dance! Tiny, because the field is reserved for robots.',
  ),
  line(
    'ivan',
    'general-41',
    'general',
    ['retry'],
    'encourage',
    'Take another look. Even my best dance routine started with me confidently facing the wall.',
  ),
  line(
    'ivan',
    'general-42',
    'general',
    ['recorded'],
    'explain',
    'Decision recorded. The DJ is keeping the commentary track muted for now.',
  ),
  line(
    'ivan',
    'general-43',
    'general',
    ['recorded'],
    'encourage',
    'Decision saved. I have put a bookmark in the playlist, not a spoiler in your match.',
  ),
  line(
    'ivan',
    'general-44',
    'general',
    ['complete'],
    'celebrate',
    'Session finished! Review first, imaginary confetti second. Yes, I made a playlist for the review too.',
  ),
  line(
    'ivan',
    'general-45',
    'general',
    ['study'],
    'explain',
    'Replay, rewind, learn. Like DJ practice, but with fewer requests to play somebody else’s favourite song.',
  ),
  line(
    'marek',
    'general-clean-build',
    'general',
    ['correct'],
    'celebrate',
    'Nicely done—my five imaginary terminals all agree that learning deserves a cheer.',
  ),
  line(
    'isa',
    'general-fair-whistle',
    'general',
    ['correct'],
    'celebrate',
    'Clear thinking! The chair approves—and for once I mean both me and the furniture.',
  ),
  line(
    'tom',
    'general-checklist',
    'general',
    ['correct'],
    'celebrate',
    'Nice work; the little rescue robot gives that answer a friendly wave.',
  ),
  line(
    'will',
    'general-kangaroo-cheer',
    'general',
    ['correct'],
    'celebrate',
    'Nicely handled, mate; that earns a little kangaroo cheer.',
  ),
  line(
    'finance',
    'general-green-cell',
    'general',
    ['correct'],
    'celebrate',
    'A neat answer for the learning ledger, with no actual accounting required.',
  ),
  line(
    'david',
    'general-express',
    'general',
    ['correct'],
    'celebrate',
    'That answer arrived clearly and neatly, just how I like my training express.',
  ),
  line(
    'jakub',
    'general-thumbs-up',
    'general',
    ['correct'],
    'celebrate',
    'Nicely done; RoboFuse sends an imaginary blink and I send a cheerful thumbs-up.',
  ),
  line(
    'caroline',
    'general-checkmark',
    'general',
    ['correct'],
    'celebrate',
    'A clear answer, a happy checkmark, and no extra task on your list.',
  ),
  line(
    'marek',
    'out-tokens',
    'out',
    ['correct'],
    'celebrate',
    'Out of bounds, but never out of tokens!',
  ),
  line(
    'marek',
    'damage-debug',
    'damaged',
    ['study', 'retry'],
    'explain',
    'My five Vim terminals volunteer for debugging duty; the robot gets a proper inspection.',
  ),
  line(
    'marek',
    'goal-commit',
    'goal',
    ['correct'],
    'celebrate',
    'That decision deserves a tidy commit and a tiny victory dance.',
  ),
  line(
    'marek',
    'own-goal-branch',
    'own-goal',
    ['study', 'retry'],
    'encourage',
    'Even my wildest feature branch needs to know which goal is which.',
  ),
  line(
    'marek',
    'pushed-review',
    'pushed-out',
    ['study'],
    'explain',
    'Let’s inspect the contact history; a robot does not come with git blame.',
  ),
  line(
    'marek',
    'restart-ready',
    'restart',
    ['correct'],
    'celebrate',
    'Ready for the next kickoff, and I only opened two more terminals.',
  ),
  line(
    'marek',
    'technical-tabs',
    'technical',
    ['study'],
    'explain',
    'Five terminals, one checklist, and absolutely no guessing the measurements.',
  ),
  line(
    'marek',
    'interference-focus',
    'interference',
    ['study', 'retry'],
    'encourage',
    'Even with unlimited imaginary tokens, the referee still needs a clear view.',
  ),
  line(
    'marek',
    'progress-loop',
    'progress',
    ['study', 'retry'],
    'encourage',
    'That looks like a good moment to check the replay instead of adding another loop.',
  ),
  line(
    'marek',
    'retry-new-tab',
    'general',
    ['retry'],
    'encourage',
    'One more look is cheaper than opening a sixth terminal, and much more useful.',
  ),
  line(
    'marek',
    'recorded-buffer',
    'general',
    ['recorded'],
    'explain',
    'Decision saved in the match log; my imaginary Vim buffer has room for more.',
  ),
  line(
    'marek',
    'recorded-tabs',
    'general',
    ['recorded'],
    'encourage',
    'Your call is logged; I’ll keep the tabs tidy while you watch the match.',
  ),
  line(
    'marek',
    'complete-tokens',
    'general',
    ['complete'],
    'celebrate',
    'Session finished, and the imaginary token budget somehow survived!',
  ),
  line(
    'marek',
    'study-first',
    'general',
    ['study'],
    'explain',
    'Read the explanation first; even my craziest idea starts with knowing the rule.',
  ),

  line(
    'isa',
    'out-boundary',
    'out',
    ['correct'],
    'celebrate',
    'Clear call! Even my chair stayed within its four-legged jurisdiction.',
  ),
  line(
    'isa',
    'damage-wasnt-me',
    'damaged',
    ['correct', 'retry', 'study'],
    'explain',
    'Damaged? Wasn’t me—I’ve been sitting here with the rulebook!',
  ),
  line(
    'isa',
    'goal-ovation',
    'goal',
    ['correct'],
    'celebrate',
    'A well-judged goal deserves a standing ovation. Yes, even from the chair.',
  ),
  line(
    'isa',
    'own-goal-labels',
    'own-goal',
    ['study', 'retry'],
    'encourage',
    'Before we cheer, let’s check which goal. My chair only has one home end.',
  ),
  line(
    'isa',
    'pushed-fair',
    'pushed-out',
    ['study'],
    'explain',
    'A fair referee checks what happened before reaching for the dramatic whistle.',
  ),
  line(
    'isa',
    'restart-whistle',
    'restart',
    ['correct'],
    'celebrate',
    'Ready for the restart. I’ll chair the proceedings, not the centre circle.',
  ),
  line(
    'isa',
    'technical-chair',
    'technical',
    ['study'],
    'explain',
    'Inspection checklist first; even the chair has to stand up to scrutiny.',
  ),
  line(
    'isa',
    'interference-crowd',
    'interference',
    ['study', 'retry'],
    'encourage',
    'Spectators have seats, referees have calls. Let’s keep those jobs separate.',
  ),
  line(
    'isa',
    'progress-chair',
    'progress',
    ['study', 'retry'],
    'encourage',
    'Let’s study the replay. I brought a chair, but not an excuse to stop paying attention.',
  ),
  line(
    'isa',
    'retry-fair',
    'general',
    ['retry'],
    'encourage',
    'Strict about the process, kind to the learner—let’s take another look.',
  ),
  line(
    'isa',
    'recorded-whistle',
    'general',
    ['recorded'],
    'explain',
    'Your call is in the log; the chair has taken a seat, not taken over.',
  ),
  line(
    'isa',
    'recorded-attention',
    'general',
    ['recorded'],
    'encourage',
    'Decision recorded. I’m keeping the minutes; my chair is keeping me upright.',
  ),
  line(
    'isa',
    'complete-chair',
    'general',
    ['complete'],
    'celebrate',
    'Training complete! The chair rises to applaud, and the actual chair gets a rest.',
  ),
  line(
    'isa',
    'study-calm',
    'general',
    ['study'],
    'explain',
    'The explanation has the details; my job is to supply a calm whistle and a big beard.',
  ),

  line(
    'tom',
    'out-maze',
    'out',
    ['correct'],
    'celebrate',
    'Nice observation; my rescue robot would now ask whether this field is a maze.',
  ),
  line(
    'tom',
    'damage-rescue',
    'damaged',
    ['study', 'retry'],
    'encourage',
    'The rescue committee can lend moral support; let’s start with the inspection notes.',
  ),
  line(
    'tom',
    'goal-launch',
    'goal',
    ['correct'],
    'celebrate',
    'Decision complete—no rocket-science calculation needed for that celebration.',
  ),
  line(
    'tom',
    'own-goal-map',
    'own-goal',
    ['study', 'retry'],
    'encourage',
    'My maze robot also appreciates checking the destination before celebrating arrival.',
  ),
  line(
    'tom',
    'pushed-maze-wall',
    'pushed-out',
    ['study'],
    'explain',
    'My rescue robot asks who moved the maze wall; the replay should have a better answer.',
  ),
  line(
    'tom',
    'restart-launchpad',
    'restart',
    ['correct'],
    'celebrate',
    'Kickoff checklist complete; please leave the rocket on its imaginary launchpad.',
  ),
  line(
    'tom',
    'technical-glasses',
    'technical',
    ['study'],
    'explain',
    'Black glasses on, checklist open: measurements beat rocket-sized guesses.',
  ),
  line(
    'tom',
    'interference-rescue',
    'interference',
    ['study', 'retry'],
    'encourage',
    'Wouldn’t happen in rescue—or at least that is what I tell my maze robot.',
  ),
  line(
    'tom',
    'progress-route',
    'progress',
    ['study', 'retry'],
    'encourage',
    'In a maze I check the route; here I’d start by checking the replay.',
  ),
  line(
    'tom',
    'retry-mission',
    'general',
    ['retry'],
    'encourage',
    'Every good mission includes a debrief, so this is a useful stop.',
  ),
  line(
    'tom',
    'recorded-log',
    'general',
    ['recorded'],
    'explain',
    'Call added to the mission log; the little rescue robot is taking notes.',
  ),
  line(
    'tom',
    'recorded-orbit',
    'general',
    ['recorded'],
    'encourage',
    'Decision recorded; I’ll keep the imaginary rocket parked while you referee.',
  ),
  line(
    'tom',
    'complete-mission',
    'general',
    ['complete'],
    'celebrate',
    'Training mission complete; the rescue committee sends a cheerful wave.',
  ),
  line(
    'tom',
    'study-toolkit',
    'general',
    ['study'],
    'explain',
    'One sourced explanation belongs in every referee’s toolkit, right next to curiosity.',
  ),

  line(
    'will',
    'out-hop',
    'out',
    ['correct'],
    'celebrate',
    'Good eye, mate; my kangaroo is impressed by your field awareness.',
  ),
  line(
    'will',
    'damage-pouch',
    'damaged',
    ['study', 'retry'],
    'encourage',
    'My kangaroo packed encouragement in its pouch; the checklist has the practical details.',
  ),
  line(
    'will',
    'goal-cheer',
    'goal',
    ['correct'],
    'celebrate',
    'A cheerful thumbs-up from the other side of the world!',
  ),
  line(
    'will',
    'own-goal-down-under',
    'own-goal',
    ['study', 'retry'],
    'encourage',
    'Being from Down Under is no excuse for mixing up the goal labels, even for my kangaroo.',
  ),
  line(
    'will',
    'pushed-elbow-room',
    'pushed-out',
    ['study'],
    'explain',
    'A kangaroo likes elbow room too; let’s watch the contact in the replay.',
  ),
  line(
    'will',
    'restart-ready',
    'restart',
    ['correct'],
    'celebrate',
    'Ready for kickoff, mate; even the kangaroo is waiting for the signal.',
  ),
  line(
    'will',
    'technical-checklist',
    'technical',
    ['study'],
    'explain',
    'Long trip, short checklist: keep the robot measurements close at hand.',
  ),
  line(
    'will',
    'interference-sidelines',
    'interference',
    ['study', 'retry'],
    'encourage',
    'The kangaroo can cheer from the audience without borrowing the referee’s whistle.',
  ),
  line(
    'will',
    'progress-hop',
    'progress',
    ['study', 'retry'],
    'encourage',
    'No rush, mate; take a hop back through the replay and watch what develops.',
  ),
  line(
    'will',
    'retry-another-look',
    'general',
    ['retry'],
    'encourage',
    'One more look, mate; learning travels well in either hemisphere.',
  ),
  line(
    'will',
    'recorded-notebook',
    'general',
    ['recorded'],
    'explain',
    'Your call is logged in the notebook; the kangaroo has kept its commentary to itself.',
  ),
  line(
    'will',
    'recorded-watching',
    'general',
    ['recorded'],
    'encourage',
    'Decision recorded, mate; keep watching and we’ll save the review for later.',
  ),
  line(
    'will',
    'complete-hemisphere',
    'general',
    ['complete'],
    'celebrate',
    'Session finished—cheers from this hemisphere and the other one!',
  ),
  line(
    'will',
    'study-perspective',
    'general',
    ['study'],
    'explain',
    'A fresh camera angle helps, even when you are already from the other side of the world.',
  ),

  line(
    'finance',
    'out-budget',
    'out',
    ['correct'],
    'celebrate',
    'Out of bounds identified; the imaginary celebration budget remains comfortably fictional.',
  ),
  line(
    'finance',
    'damage-sheet',
    'damaged',
    ['study', 'retry'],
    'explain',
    'My spreadsheet has a repair column, but the inspection checklist gets the final word.',
  ),
  line(
    'finance',
    'goal-cell',
    'goal',
    ['correct'],
    'celebrate',
    'A tidy decision deserves a very enthusiastic green spreadsheet cell.',
  ),
  line(
    'finance',
    'own-goal-column',
    'own-goal',
    ['study', 'retry'],
    'encourage',
    'Let’s double-check the team column before my pretend quarterly report gets excited.',
  ),
  line(
    'finance',
    'pushed-audit',
    'pushed-out',
    ['study'],
    'explain',
    'Time for a friendly contact audit; my imaginary board likes a clear replay.',
  ),
  line(
    'finance',
    'restart-agenda',
    'restart',
    ['correct'],
    'celebrate',
    'Next item on the agenda: kickoff, with absolutely no meeting about the meeting.',
  ),
  line(
    'finance',
    'technical-units',
    'technical',
    ['study'],
    'explain',
    'A beautiful spreadsheet still needs the right units and actual measurements.',
  ),
  line(
    'finance',
    'interference-boardroom',
    'interference',
    ['study', 'retry'],
    'encourage',
    'The audience is not a board meeting; let’s give the referee room to observe.',
  ),
  line(
    'finance',
    'progress-dashboard',
    'progress',
    ['study', 'retry'],
    'encourage',
    'My fictional dashboard can wait while we look carefully at the match replay.',
  ),
  line(
    'finance',
    'retry-invest-learning',
    'general',
    ['retry'],
    'encourage',
    'No money involved: today’s only investment is another careful look at the explanation.',
  ),
  line(
    'finance',
    'recorded-ledger',
    'general',
    ['recorded'],
    'explain',
    'Your decision has its own row in the match log; no spreadsheet verdict attached.',
  ),
  line(
    'finance',
    'recorded-paperwork',
    'general',
    ['recorded'],
    'encourage',
    'Call recorded; I’ll handle the imaginary paperwork while you watch the field.',
  ),
  line(
    'finance',
    'complete-roi',
    'general',
    ['complete'],
    'celebrate',
    'Session complete—my entirely fictional ROI report says we collected plenty of practice.',
  ),
  line(
    'finance',
    'study-small-print',
    'general',
    ['study'],
    'explain',
    'Read the sourced explanation; for once, the useful details are not hidden in tiny print.',
  ),

  line(
    'david',
    'out-platform',
    'out',
    ['correct'],
    'celebrate',
    'A clear observation, delivered with express-train precision.',
  ),
  line(
    'david',
    'damage-depot',
    'damaged',
    ['study', 'retry'],
    'encourage',
    'Even a favourite locomotive visits the depot; let’s check the robot’s inspection notes.',
  ),
  line(
    'david',
    'goal-whistle',
    'goal',
    ['correct'],
    'celebrate',
    'That decision gets one cheerful whistle from the training conductor.',
  ),
  line(
    'david',
    'own-goal-destination',
    'own-goal',
    ['study', 'retry'],
    'encourage',
    'Check the destination board before celebrating the arrival.',
  ),
  line(
    'david',
    'pushed-coupling',
    'pushed-out',
    ['study'],
    'explain',
    'Train carriages are built for coupling; this robot contact deserves its own careful replay.',
  ),
  line(
    'david',
    'restart-signal',
    'restart',
    ['correct'],
    'celebrate',
    'Kickoff signal received; the referee training express is ready to depart.',
  ),
  line(
    'david',
    'technical-gauge',
    'technical',
    ['study'],
    'explain',
    'Whether checking a rail gauge or a robot, read the measurement instead of guessing.',
  ),
  line(
    'david',
    'interference-platform',
    'interference',
    ['study', 'retry'],
    'encourage',
    'A clear view helps every volunteer, just like a readable platform sign.',
  ),
  line(
    'david',
    'progress-timetable',
    'progress',
    ['study', 'retry'],
    'encourage',
    'My timetable is patient enough for another look at how this situation developed.',
  ),
  line(
    'david',
    'retry-training-stop',
    'general',
    ['retry'],
    'encourage',
    'This is a training stop, not a missed train; let’s walk through the explanation.',
  ),
  line(
    'david',
    'recorded-logbook',
    'general',
    ['recorded'],
    'explain',
    'Decision entered in the conductor’s logbook; the match stays in your hands.',
  ),
  line(
    'david',
    'recorded-timetable',
    'general',
    ['recorded'],
    'encourage',
    'Your call is logged; I’ll keep the imaginary timetable while you watch the robots.',
  ),
  line(
    'david',
    'complete-station',
    'general',
    ['complete'],
    'celebrate',
    'Final training station reached; thank you for giving referee practice a proper seat.',
  ),
  line(
    'david',
    'study-volunteers',
    'general',
    ['study'],
    'explain',
    'A clear explanation helps the next volunteer too, so let’s read it together.',
  ),

  line(
    'jakub',
    'out-camera',
    'out',
    ['correct'],
    'celebrate',
    'Good field awareness; now I can stop asking the livestream camera for another angle.',
  ),
  line(
    'jakub',
    'damage-module',
    'damaged',
    ['study', 'retry'],
    'encourage',
    'Let’s check the robot before I volunteer another RoboFuse communication module.',
  ),
  line(
    'jakub',
    'goal-livestream',
    'goal',
    ['correct'],
    'celebrate',
    'That decision is ready for the replay reel; Caroline, I remembered to press record!',
  ),
  line(
    'jakub',
    'own-goal-caption',
    'own-goal',
    ['study', 'retry'],
    'encourage',
    'Let’s check the team labels before the livestream caption gets ahead of us.',
  ),
  line(
    'jakub',
    'pushed-long-sticks',
    'pushed-out',
    ['study'],
    'explain',
    'My long sticks stay off the field; this contact needs a replay, not a longer reach.',
  ),
  line(
    'jakub',
    'restart-link',
    'restart',
    ['correct'],
    'celebrate',
    'Kickoff signal ready; my imaginary RoboFuse module gives a tiny approving blink.',
  ),
  line(
    'jakub',
    'technical-ball',
    'technical',
    ['study'],
    'explain',
    'Tiny IR ball, ESP/OLED module, big checklist. Why are my smallest gadgets always the busiest?',
  ),
  line(
    'jakub',
    'interference-stream',
    'interference',
    ['study', 'retry'],
    'encourage',
    'The livestream gets commentary; the robots do not need directions from the audience.',
  ),
  line(
    'jakub',
    'progress-delegate',
    'progress',
    ['study', 'retry'],
    'encourage',
    'I could delegate another camera task, or we could simply watch this replay carefully.',
  ),
  line(
    'jakub',
    'retry-checklist',
    'general',
    ['retry'],
    'encourage',
    'Another careful look is allowed; even my task list gets revised.',
  ),
  line(
    'jakub',
    'recorded-stream',
    'general',
    ['recorded'],
    'explain',
    'Call recorded; the virtual livestream keeps rolling without a verdict from me.',
  ),
  line(
    'jakub',
    'recorded-module',
    'general',
    ['recorded'],
    'encourage',
    'Your decision is in the log; my tiny ESP/OLED display is quietly keeping me company.',
  ),
  line(
    'jakub',
    'complete-long-sticks',
    'general',
    ['complete'],
    'celebrate',
    'Session complete—Caroline gets the thanks; I get to carry the very long sticks.',
  ),
  line(
    'jakub',
    'study-source',
    'general',
    ['study'],
    'explain',
    'A good module needs a clear signal, and a good referee needs the sourced explanation.',
  ),

  line(
    'caroline',
    'out-framing',
    'out',
    ['correct'],
    'celebrate',
    'Nice observation; that deserves a camera angle with absolutely nobody blocking it.',
  ),
  line(
    'caroline',
    'damage-task-list',
    'damaged',
    ['study', 'retry'],
    'encourage',
    'Inspection first; I’ll stop Jakub from adding three unrelated jobs to the task list.',
  ),
  line(
    'caroline',
    'goal-highlight',
    'goal',
    ['correct'],
    'celebrate',
    'That decision can have a highlight clip; I already checked the camera is recording.',
  ),
  line(
    'caroline',
    'own-goal-graphics',
    'own-goal',
    ['study', 'retry'],
    'encourage',
    'Let’s read the team labels before anyone orders the celebratory livestream graphic.',
  ),
  line(
    'caroline',
    'pushed-clear-view',
    'pushed-out',
    ['study'],
    'explain',
    'A clear replay beats five people leaning in front of the camera.',
  ),
  line(
    'caroline',
    'restart-ready',
    'restart',
    ['correct'],
    'celebrate',
    'Ready for kickoff, and yes, Jakub, the livestream is already ready too.',
  ),
  line(
    'caroline',
    'technical-list',
    'technical',
    ['study'],
    'explain',
    'One checklist at a time; a communication module cannot organise the whole task list.',
  ),
  line(
    'caroline',
    'interference-audience',
    'interference',
    ['study', 'retry'],
    'encourage',
    'The audience gets a great view, not a steering wheel.',
  ),
  line(
    'caroline',
    'progress-replay',
    'progress',
    ['study', 'retry'],
    'encourage',
    'Let’s watch the replay before Jakub delegates the mystery to another volunteer.',
  ),
  line(
    'caroline',
    'retry-retake',
    'general',
    ['retry'],
    'encourage',
    'Training is allowed another take; the explanation is ready when you are.',
  ),
  line(
    'caroline',
    'recorded-cue',
    'general',
    ['recorded'],
    'explain',
    'Your call is logged; I’ll keep the virtual camera on the field.',
  ),
  line(
    'caroline',
    'recorded-task',
    'general',
    ['recorded'],
    'encourage',
    'Decision recorded, one task checked off, and no surprise verdict from the commentary desk.',
  ),
  line(
    'caroline',
    'complete-wrap',
    'general',
    ['complete'],
    'celebrate',
    'That’s a wrap—session finished, cameras resting, and Jakub can carry the imaginary cables.',
  ),
  line(
    'caroline',
    'study-explanation',
    'general',
    ['study'],
    'explain',
    'The useful explanation is already here; no need to wait for the livestream director.',
  ),
];
